version: '3'
services:
  compose-api:
    container_name: apihost
    image: "compose-api"
    build: api/
    ports:
    - "8080:8080"
  compose-ui:
    image: "compose-ui"
    build: ui/
    ports:
    - "8081:8081"
    depends_on:
      - compose-api
